HCC: hc::extent< N > Class Template Reference
hc::extent< N > Class Template Reference
Represents a unique position in N-dimensional space.
#include <hc.hpp>
Public Types
typedef int value_type
The element type of extent<N>.
Public Member Functions
extent () __CPU__ __HC__
Default constructor.
extent (const extent &other) __CPU__ __HC__
Copy constructor.
extent (const int components[]) __CPU__ __HC__
Constructs an extent<N> with the coordinate values provided the array of int component values.
extent (int components[]) __CPU__ __HC__
Constructs an extent<N> with the coordinate values provided the array of int component values.
extent & operator= (const extent &other) __CPU__ __HC__
Assigns the component values of "other" to this extent<N> object.
bool contains (const index< N > &idx) const __CPU__ __HC__
Tests whether the index "idx" is properly contained within this extent (with an assumed origin of zero).
unsigned int size () const __CPU__ __HC__
This member function returns the total linear size of this extent<N> (in units of elements), which is computed as: extent[0] * extent[1] ...
extent (int e0) __CPU__ __HC__
Constructs an extent<N> with the coordinate values provided by .
template<typename... _Tp>
extent (_Tp...__t) __CPU__ __HC__
Constructs an extent<N> with the coordinate values provided by .
int operator[] (unsigned int c) const __CPU__ __HC__
Returns the extent component value at position c.
int & operator[] (unsigned int c) __CPU__ __HC__
Returns the extent component value at position c.
tiled_extent< 1 > tile (int t0) const
Produces a tiled_extent object with the tile extents given by t0, t1, and t2.
tiled_extent< 2 > tile (int t0, int t1) const
Produces a tiled_extent object with the tile extents given by t0, t1, and t2.
tiled_extent< 3 > tile (int t0, int t1, int t2) const
Produces a tiled_extent object with the tile extents given by t0, t1, and t2.
tiled_extent< 1 > tile_with_dynamic (int t0, int dynamic_size) const
Produces a tiled_extent object with the tile extents given by t0, t1, and t2, plus a certain amount of dynamic group segment.
tiled_extent< 2 > tile_with_dynamic (int t0, int t1, int dynamic_size) const
Produces a tiled_extent object with the tile extents given by t0, t1, and t2, plus a certain amount of dynamic group segment.
tiled_extent< 3 > tile_with_dynamic (int t0, int t1, int t2, int dynamic_size) const
Produces a tiled_extent object with the tile extents given by t0, t1, and t2, plus a certain amount of dynamic group segment.
bool operator== (const extent &other) const __CPU__ __HC__
Compares two objects of extent<N>.
bool operator!= (const extent &other) const __CPU__ __HC__
Compares two objects of extent<N>.
extent & operator+= (const extent &__r) __CPU__ __HC__
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
extent & operator-= (const extent &__r) __CPU__ __HC__
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
extent & operator*= (const extent &__r) __CPU__ __HC__
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
extent & operator/= (const extent &__r) __CPU__ __HC__
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
extent & operator%= (const extent &__r) __CPU__ __HC__
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
extent operator+ (const index< N > &idx) __CPU__ __HC__
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
extent operator- (const index< N > &idx) __CPU__ __HC__
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
extent & operator+= (const index< N > &idx) __CPU__ __HC__
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
extent & operator-= (const index< N > &idx) __CPU__ __HC__
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
extent & operator+= (int value) __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) value.
extent & operator-= (int value) __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) value.
extent & operator*= (int value) __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) value.
extent & operator/= (int value) __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) value.
extent & operator%= (int value) __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) value.
extent & operator++ () __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) 1.
extent operator++ (int) __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) 1.
extent & operator-- () __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) 1.
extent operator-- (int) __CPU__ __HC__
For a given operator , produces the same effect as (*this) = (*this) 1.
Static Public Attributes
static const int rank = N
A static member of extent<N> that contains the rank of this extent.
Friends
template<int K, typename Q >
struct Kalmar::index_helper
template<int K, typename Q1 , typename Q2 >
struct Kalmar::amp_helper
Detailed Description
template<int N>
class hc::extent< N >
Represents a unique position in N-dimensional space.
Template Parameters
N The dimension to this extent applies. Special constructors are supplied for the cases where , but N can be any integer greater than or equal to 1.
Constructor & Destructor Documentation
template<int N> hc::extent< N >::extent () inline
Default constructor.
The value at each dimension is initialized to zero. Thus, "extent<3> ix;" initializes the variable to the position (0,0,0).
Referenced by hc::array< T, N >::operator=(), hc::array_view< T, N >::operator=(), and hc::array_view< const T, N >::operator=().
template<int N> hc::extent< N >::extent (const extent< N > & other) inline
Copy constructor.
Constructs a new extent<N> from the supplied argument.
Parameters
other An object of type extent<N> from which to initialize this new extent.
template<int N> hc::extent< N >::extent (int e0) inline explicit
Constructs an extent<N> with the coordinate values provided by .
These are specialized constructors that are only valid when the rank of the extent . Invoking a specialized constructor whose argument will result in a compilation error.
Parameters
[in] e0 The component values of the extent vector.
template<int N> template<typename... _Tp> hc::extent< N >::extent (_Tp... __t) inline explicit
Constructs an extent<N> with the coordinate values provided by .
These are specialized constructors that are only valid when the rank of the extent . Invoking a specialized constructor whose argument will result in a compilation error.
Parameters
[in] e0 The component values of the extent vector.
template<int N> hc::extent< N >::extent (const int components[]) inline explicit
Constructs an extent<N> with the coordinate values provided the array of int component values.
If the coordinate array length N, the behavior is undefined. If the array value is NULL or not a valid pointer, the behavior is undefined.
Parameters
[in] components An array of N int values.
template<int N> hc::extent< N >::extent (int components[]) inline explicit
Constructs an extent<N> with the coordinate values provided the array of int component values.
If the coordinate array length N, the behavior is undefined. If the array value is NULL or not a valid pointer, the behavior is undefined.
Parameters
[in] components An array of N int values.
Member Function Documentation
template<int N> bool hc::extent< N >::contains (const index< N > & idx) const inline
Tests whether the index "idx" is properly contained within this extent (with an assumed origin of zero).
Parameters
[in] idx An object of type index<N>
Returns
Returns true if the "idx" is contained within the space defined by this extent (with an assumed origin of zero).
template<int N> bool hc::extent< N >::operator!= (const extent< N > & other) const inline
Compares two objects of extent<N>.
The expression leftExt rightExt is true if leftExt[i] rightExt[i] for every i from 0 to N-1.
Parameters
[in] other The right-hand extent<N> to be compared.
template<int N> extent& hc::extent< N >::operator%= (const extent< N > & __r) inline
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] ext[i]
Parameters
[in] ext The right-hand extent<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator%= (int value) inline
For a given operator , produces the same effect as (*this) = (*this) value.
The return value is "*this".
Parameters
[in] value The right-hand int of the arithmetic operation.
template<int N> extent& hc::extent< N >::operator*= (const extent< N > & __r) inline
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] ext[i]
Parameters
[in] ext The right-hand extent<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator*= (int value) inline
For a given operator , produces the same effect as (*this) = (*this) value.
The return value is "*this".
Parameters
[in] value The right-hand int of the arithmetic operation.
template<int N> extent hc::extent< N >::operator+ (const index< N > & idx) inline
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] idx[i]
Parameters
[in] idx The right-hand index<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator++ () inline
For a given operator , produces the same effect as (*this) = (*this) 1.
For prefix increment and decrement, the return value is "*this". Otherwise a new extent<N> is returned.
template<int N> extent hc::extent< N >::operator++ (int) inline
For a given operator , produces the same effect as (*this) = (*this) 1.
For prefix increment and decrement, the return value is "*this". Otherwise a new extent<N> is returned.
template<int N> extent& hc::extent< N >::operator+= (const extent< N > & __r) inline
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] ext[i]
Parameters
[in] ext The right-hand extent<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator+= (const index< N > & idx) inline
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] idx[i]
Parameters
[in] idx The right-hand index<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator+= (int value) inline
For a given operator , produces the same effect as (*this) = (*this) value.
The return value is "*this".
Parameters
[in] value The right-hand int of the arithmetic operation.
template<int N> extent hc::extent< N >::operator- (const index< N > & idx) inline
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] idx[i]
Parameters
[in] idx The right-hand index<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator-- () inline
For a given operator , produces the same effect as (*this) = (*this) 1.
For prefix increment and decrement, the return value is "*this". Otherwise a new extent<N> is returned.
template<int N> extent hc::extent< N >::operator-- (int) inline
For a given operator , produces the same effect as (*this) = (*this) 1.
For prefix increment and decrement, the return value is "*this". Otherwise a new extent<N> is returned.
template<int N> extent& hc::extent< N >::operator-= (const extent< N > & __r) inline
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] ext[i]
Parameters
[in] ext The right-hand extent<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator-= (const index< N > & idx) inline
Adds (or subtracts) an object of type index<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] idx[i]
Parameters
[in] idx The right-hand index<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator-= (int value) inline
For a given operator , produces the same effect as (*this) = (*this) value.
The return value is "*this".
Parameters
[in] value The right-hand int of the arithmetic operation.
template<int N> extent& hc::extent< N >::operator/= (const extent< N > & __r) inline
Adds (or subtracts) an object of type extent<N> from this extent to form a new extent.
The result extent<N> is such that for a given operator , result[i] = this[i] ext[i]
Parameters
[in] ext The right-hand extent<N> to be added or subtracted.
template<int N> extent& hc::extent< N >::operator/= (int value) inline
For a given operator , produces the same effect as (*this) = (*this) value.
The return value is "*this".
Parameters
[in] value The right-hand int of the arithmetic operation.
template<int N> extent& hc::extent< N >::operator= (const extent< N > & other) inline
Assigns the component values of "other" to this extent<N> object.
Parameters
[in] other An object of type extent<N> from which to copy into this extent.
Returns
Returns *this.
template<int N> bool hc::extent< N >::operator== (const extent< N > & other) const inline
Compares two objects of extent<N>.
The expression leftExt rightExt is true if leftExt[i] rightExt[i] for every i from 0 to N-1.
Parameters
[in] other The right-hand extent<N> to be compared.
template<int N> int hc::extent< N >::operator[] (unsigned int c) const inline
Returns the extent component value at position c.
Parameters
[in] c The dimension axis whose coordinate is to be accessed.
Returns
A the component value at position c.
template<int N> int& hc::extent< N >::operator[] (unsigned int c) inline
Returns the extent component value at position c.
Parameters
[in] c The dimension axis whose coordinate is to be accessed.
Returns
A the component value at position c.
template<int N> unsigned int hc::extent< N >::size () const inline
This member function returns the total linear size of this extent<N> (in units of elements), which is computed as: extent[0] * extent[1] ...
extent[N-1]
Referenced by hc::array< T, N >::array(), hc::array_view< T, N >::array_view(), hc::array_view< const T, N >::array_view(), hc::array< T, N >::operator std::vector< T >(), hc::array< T, N >::reinterpret_as(), hc::array_view< T, N >::reinterpret_as(), hc::array_view< const T, N >::reinterpret_as(), hc::array< T, N >::view_as(), hc::array_view< T, N >::view_as(), and hc::array_view< const T, N >::view_as().
template<int N> tiled_extent< 1 > hc::extent< N >::tile (int t0) const inline
Produces a tiled_extent object with the tile extents given by t0, t1, and t2.
tile(t0, t1, t2) is only supported on extent<1>. It will produce a compile-time error if used on an extent where N 3. tile(t0, t1) is only supported on extent<2>. It will produce a compile-time error if used on an extent where N 2. tile(t0) is only supported on extent<1>. It will produce a compile-time error if used on an extent where N 1.
template<int N> tiled_extent< 2 > hc::extent< N >::tile (int t0, int t1) const inline
Produces a tiled_extent object with the tile extents given by t0, t1, and t2.
tile(t0, t1, t2) is only supported on extent<1>. It will produce a compile-time error if used on an extent where N 3. tile(t0, t1) is only supported on extent<2>. It will produce a compile-time error if used on an extent where N 2. tile(t0) is only supported on extent<1>. It will produce a compile-time error if used on an extent where N 1.
template<int N> tiled_extent< 3 > hc::extent< N >::tile (int t0, int t1, int t2) const inline
Produces a tiled_extent object with the tile extents given by t0, t1, and t2.
tile(t0, t1, t2) is only supported on extent<1>. It will produce a compile-time error if used on an extent where N 3. tile(t0, t1) is only supported on extent<2>. It will produce a compile-time error if used on an extent where N 2. tile(t0) is only supported on extent<1>. It will produce a compile-time error if used on an extent where N 1.
The documentation for this class was generated from the following file:
/home/scchan/code/hcc/include/hc.hpp